### ISSUE TITLE
Why not use `flush()` or `persistAndFlush()` here?

### ISSUE THREAD

**Issue by macbesu** [mikro-orm/express-ts-example-app#5]
Hi I've used the following code from the [example](https://github.com/mikro-orm/express-ts-example-app/blob/e875544b9f6d1ba822c37be82ab0d90564f8e0e3/app/controllers/book.controller.ts) to insert a new record, but the new entity was not written to the database. However, using `persistAndFlush()` instead of `persist()` works. Any problem here?

https://github.com/mikro-orm/express-ts-example-app/blob/e875544b9f6d1ba822c37be82ab0d90564f8e0e3/app/controllers/book.controller.ts#L37

**Comment by fecony** [comment]
Hi!

Same issue here, looks like author forgot about flush, 
Documentation says "`em.persist(entity)` is used to mark new entities for future persisting. It will make the entity managed by given `EntityManager` and once `flush` will be called, it will be written to the database."

`em.flush()` is never called so data is not written to database.

@B4nan Could you fix it, or if it is okay I can make PR for this?
